if sender_string is empty, Skebby ignore the sender_numser and uses t…
fazland/skebby-rest-client pull request #8
Opened 2017-07-03 11:48 UTC by AntonioNigro

…he Default sender set in the Administration Panel

2017-07-04 07:16 UTC, alekitto requested changes
Good point! And thanks for your contribution.

It seems that your modifications broke the test suite. Can you please fix that and add a test case for this scenario?
I also left some style comments

2017-07-04 07:16 UTC, alekitto commented on lib/Client/Client.php
> +        //
Prefer `/* ... */` for multiline comments.

2017-07-04 07:16 UTC, alekitto commented on lib/Client/Client.php
> +        if (trim($request['sender_string']) == '') {
Please use `===` for strict comparison.

2017-08-08 10:19 UTC, p365labs commented
@AntonioNigro any chances you can update ur PR ? tnx

2017-08-08 11:49 UTC, AntonioNigro commented
Sorry, full of tasks! Next week i will :)

2017-08-08 19:59 UTC, AntonioNigro commented
There is no need for a new test class, just cleaned up the test provided: the query string doesn't need an empty sender_string param. A new test class should be the same as ClientTest. Tnx

2017-08-09 07:46 UTC, alekitto approved these changes

2017-08-09 07:47 UTC, merged

2017-08-09 07:47 UTC, alekitto commented
Thanks @AntonioNigro